AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: hol

Globals:
  Function:
    Timeout: 5

Resources:
  HoLFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hol_lambda/
      Environment:
        Variables:
          DDBTable: !Ref DDBTable
      Handler: app.lambda_handler
      Runtime: python3.6
      Events:
        IoTRule:
          Type: IoTRule
          Properties:
            Sql: SELECT * FROM 'smarthome/house1/energy/appliances'
      FunctionName: hol_lambda_sam
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DDBTable

  DDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: device_id
        AttributeType: S
      - AttributeName: timestamp
        AttributeType: S
      KeySchema:
      - AttributeName: device_id
        KeyType: HASH
      - AttributeName: timestamp
        KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
